keys:
  # admin
  - &julien age1689xa07eghw2se09xky5gvnuse63y50myw7qt5ytq0ryganm4scsc83jqa
  # cloud user
  - &cosimo age1a2tfqjg8r8483qel7maf5whf6vmynwj4l57da5q935cta8tenymqwh9guj
creation_rules:
  - path_regex: hosts/secrets.(yaml|json)$
    key_groups:
    - age:
      - *julien
      - *cosimo
  - path_regex: hosts/julien/secrets.(yaml|json)$
    key_groups:
    - age:
      - *julien
  - path_regex: hosts/cosimo/secrets.(yaml|json)$
    key_groups:
    - age:
      - *julien
      - *cosimo
