keys:
  - &julien age1g4ltdl65a2rsl64dl3rv4skh0cv72kg6knqfyxxqdhhvnryl5f5qq5f4lv
creation_rules:
  - path_regex: secrets.json$
    key_groups:
    - age:
      - *julien
  - path_regex: hosts/julien/secrets.json$
    key_groups:
    - age:
      - *julien
