keys:
  # admin
  - &julien age1689xa07eghw2se09xky5gvnuse63y50myw7qt5ytq0ryganm4scsc83jqa
  - &dorothy age1p3e9qvz8ykl0wz6rq2h5vxawyv2t93629c259qgstnmwdzrl95fshuplqk
  # cloud user
  - &cosimo age1xanc87qd0wk8srg479lz9pac8fwafhy3efm6csgx2kkm3h6jrgvsz4zxgs
  - &chabert age1xj8kk5s7apjweunys70xppzm5cddv94y9w9sxexy8w25zdj8d4fqntch6m
  - &barnabars age16dupulv4hv6exygccwtershxet9kap7h8nffykympp4n4u4z7a2seaqwvh
  - &sheep age1v32nph0733pmw3d5kyhhny35045cx7fvsfjh50hn9p0jc9x2t4aqp3r3ww
  - &karenina age1kcflwrpg5sthhh78ddxwf64u0uqhlu5tyasqr2vpngkn7pqw2d2sxzma6h
creation_rules:
  - path_regex: hosts/(\w+/)*secrets(\.\w+)?\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *julien
      - *dorothy
      - *cosimo
      - *chabert
      - *barnabars
      - *sheep
      - *karenina
