keys:
  # admin
  - &julien age1689xa07eghw2se09xky5gvnuse63y50myw7qt5ytq0ryganm4scsc83jqa
  - &dorothy age1p3e9qvz8ykl0wz6rq2h5vxawyv2t93629c259qgstnmwdzrl95fshuplqk
  - &bendemann age1zr2786mpjddgyhggkrn6v0puncpa7g9pycr480q9px9xe3wsf4dqhe7j48
  # cloud user
  - &chabert age1688nvud2hlyznkxk7mfamhm5e294f2t7y8q78ck9f89n85zlsq9qa56za5
  - &barnabars age16dupulv4hv6exygccwtershxet9kap7h8nffykympp4n4u4z7a2seaqwvh
  - &sheep age1pmyfed8ax3626wq5ff96v5sdpeqrdjdlwt0znz8xcul7nht0ss6q9jwvyd
  - &karenina age1kcflwrpg5sthhh78ddxwf64u0uqhlu5tyasqr2vpngkn7pqw2d2sxzma6h
creation_rules:
  - path_regex: hosts/(\w+/)*secrets(\.\w+)?\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *julien
      - *dorothy
      - *chabert
      - *barnabars
      - *sheep
      - *karenina
      - *bendemann
  - path_regex: hosts/sheep/services/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dorothy
      - *sheep
