{
  config,
  ...
}:

{
  topology.self.interfaces = {
    lo = {
      addresses = [ "127.0.0.1" ];
      type = "loopback";
    };
    wlp1s0 = {
      addresses = [ "192.168.31.111" ];
    };
  };

  networking.hostName = "dorothy";
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    nssmdns6 = true;
    publish = {
      enable = true;
      addresses = true;
      domain = true;
    };
  };

  sops.secrets = {
    hometown-wifip = { };
    homehome-wifip = { };
    homestore-wifip = { };
    university-dormitory-wifip = { };
    mobile-hotspot-wifip = { };
    county-wifi-ssid = { };
    county-wifip = { };
    mogan-wifi-ssid = { };
    mogan-wifip = { };
    moganh-wifi-ssid = { };
    moganh-wifip = { };
  };
  sops.templates.nmenv.content = with config.sops.placeholder; ''
    HOMETOWN_WIFI_PWD=${hometown-wifip}
    HOMEHOME_WIFI_PWD=${homehome-wifip}
    HOMESTORE_WIFI_PWD=${homestore-wifip}
    UNIVERSITY_DORMITORY_WIFI_PWD=${university-dormitory-wifip}
    MOBILE_HOTSPOT_WIFI_PWD=${mobile-hotspot-wifip}
    COUNTY_WIFI_SSID=${county-wifi-ssid}
    COUNTY_WIFI_PWD=${county-wifip}
    MOGAN_WIFI_SSID=${mogan-wifi-ssid}
    MOGAN_WIFI_PWD=${mogan-wifip}
    MOGANH_WIFI_SSID=${moganh-wifi-ssid}
    MOGANH_WIFI_PWD=${moganh-wifip}
  '';
  networking.networkmanager = {
    enable = true;
    # generated by https://github.com/Janik-Haag/nm2nix
    ensureProfiles = {
      environmentFiles = [ config.sops.templates.nmenv.path ];
      profiles = {
        hometown = {
          connection = {
            id = "hometown";
            interface-name = "wlp1s0";
            type = "wifi";
            uuid = "98091613-9c55-4698-ad40-b7d2528e95cc";
          };
          ipv4 = {
            method = "auto";
          };
          ipv6 = {
            addr-gen-mode = "default";
            method = "auto";
          };
          proxy = { };
          wifi = {
            mode = "infrastructure";
            ssid = "TP-LINK_6A59";
          };
          wifi-security = {
            auth-alg = "open";
            key-mgmt = "wpa-psk";
            psk = "$HOMETOWN_WIFI_PWD";
          };
        };
        homehome = {
          connection = {
            id = "homehome";
            interface-name = "wlp1s0";
            type = "wifi";
            uuid = "31b1f0c9-9cd5-4939-add7-e3a073518e1b";
          };
          ipv4 = {
            method = "auto";
          };
          ipv6 = {
            addr-gen-mode = "default";
            method = "auto";
          };
          proxy = { };
          wifi = {
            mode = "infrastructure";
            ssid = "ChinaNet-cyFh";
          };
          wifi-security = {
            auth-alg = "open";
            key-mgmt = "wpa-psk";
            psk = "$HOMEHOME_WIFI_PWD";
          };
        };
        homestore = {
          connection = {
            id = "homestore";
            interface-name = "wlp1s0";
            type = "wifi";
            uuid = "8f6d9ec5-40be-4486-b9f2-3a35c4a05ec7";
          };
          ipv4 = {
            method = "auto";
          };
          ipv6 = {
            addr-gen-mode = "default";
            method = "auto";
          };
          proxy = { };
          wifi = {
            mode = "infrastructure";
            ssid = "ChinaNet-59Hz-5G";
          };
          wifi-security = {
            auth-alg = "open";
            key-mgmt = "wpa-psk";
            psk = "$HOMESTORE_WIFI_PWD";
          };
        };
        university-dormitory = {
          connection = {
            id = "university-dormitory";
            interface-name = "wlp1s0";
            type = "wifi";
            uuid = "d83c8958-5019-4099-8d6b-7d8339612c6a";
          };
          # ipv4 = { method = "manual"; address1 = "192.168.31.111/24,192.168.31.86"; dns = "1.1.1.1;"; };
          ipv4 = {
            method = "manual";
            address1 = "192.168.31.111/24,192.168.31.1";
            dns = "1.1.1.1;";
          };
          # ipv4 = { method = "auto"; };
          ipv6 = {
            addr-gen-mode = "default";
            method = "auto";
          };
          proxy = { };
          wifi = {
            mode = "infrastructure";
            ssid = "abort";
          };
          wifi-security = {
            auth-alg = "open";
            key-mgmt = "wpa-psk";
            psk = "$UNIVERSITY_DORMITORY_WIFI_PWD";
          };
        };
        mobile-hotspot = {
          connection = {
            id = "mobile-hotspot";
            interface-name = "wlp1s0";
            timestamp = "1724937443";
            type = "wifi";
            uuid = "dfa9fcd3-97a7-4ad8-adee-c40dd68d66c5";
          };
          ipv4 = {
            method = "auto";
          };
          ipv6 = {
            addr-gen-mode = "default";
            method = "auto";
          };
          proxy = { };
          wifi = {
            mode = "infrastructure";
            ssid = "xkcd";
          };
          wifi-security = {
            auth-alg = "open";
            key-mgmt = "wpa-psk";
            psk = "$MOBILE_HOTSPOT_WIFI_PWD";
          };
        };
        county = {
          connection = {
            id = "county";
            interface-name = "wlp1s0";
            type = "wifi";
            uuid = "acb32f3b-272f-457c-88da-f887c489389a";
          };
          ipv4 = {
            method = "auto";
          };
          ipv6 = {
            addr-gen-mode = "default";
            method = "auto";
          };
          proxy = { };
          wifi = {
            mode = "infrastructure";
            ssid = "$COUNTY_WIFI_SSID";
          };
          wifi-security = {
            auth-alg = "open";
            key-mgmt = "wpa-psk";
            psk = "$COUNTY_WIFI_PWD";
          };
        };
        mogan = {
          connection = {
            id = "mogan";
            interface-name = "wlp1s0";
            type = "wifi";
            uuid = "524d7cd5-b5ea-4c7d-a4da-327f4bccfb60";
          };
          ipv4 = {
            method = "auto";
          };
          ipv6 = {
            addr-gen-mode = "default";
            method = "auto";
          };
          proxy = { };
          wifi = {
            mode = "infrastructure";
            ssid = "$MOGAN_WIFI_SSID";
          };
          wifi-security = {
            auth-alg = "open";
            key-mgmt = "wpa-psk";
            psk = "$MOGAN_WIFI_PWD";
          };
        };
        moganH = {
          connection = {
            id = "moganH";
            interface-name = "wlp1s0";
            type = "wifi";
            uuid = "47e40f36-9917-4529-852b-59cd385b8a4f";
          };
          ipv4 = {
            method = "auto";
          };
          ipv6 = {
            addr-gen-mode = "default";
            method = "auto";
          };
          proxy = { };
          wifi = {
            mode = "infrastructure";
            ssid = "$MOGANH_WIFI_SSID";
          };
          wifi-security = {
            auth-alg = "open";
            key-mgmt = "wpa-psk";
            psk = "$MOGANH_WIFI_PWD";
          };
        };
      };
    };
  };

  networking.firewall.enable = false;
  networking.nftables = {
    enable = true;
    rulesetFile = ./components/rules.nft;
  };
}
